### ISSUE TITLE
[*] Checking  Internet Connection mafia.sh: line 35: nc: command not found \033[1;38;5;196mNo Internet Connection

### ISSUE THREAD

**Issue by tiktok-unlimited-followers** [machine1337/mafiahacks#4]
[*] Checking  Internet Connection
mafia.sh: line 35: nc: command not found
\033[1;38;5;196mNo Internet Connection

**Comment by machine1337** [comment]
@tiktok-unlimited-followers sudo apt-get install netcat

**Comment by tiktok-unlimited-followers** [comment]
Thanks, Done.
